// <auto-generated />
using BolomorzKeyManager.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BolomorzKeyManager.Model.Migrations
{
    [DbContext(typeof(KeyManagerContext))]
    partial class KeyManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BolomorzKeyManager.Model.Key", b =>
                {
                    b.Property<int>("KID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedData")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("UAID")
                        .HasColumnType("INTEGER");

                    b.HasKey("KID");

                    b.HasIndex("UAID");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("BolomorzKeyManager.Model.Password", b =>
                {
                    b.Property<int>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedData")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("UAID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PID");

                    b.HasIndex("UAID");

                    b.ToTable("Passwords");
                });

            modelBuilder.Entity("BolomorzKeyManager.Model.UserAccount", b =>
                {
                    b.Property<int>("UAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashParameter")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UAID");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("BolomorzKeyManager.Model.Key", b =>
                {
                    b.HasOne("BolomorzKeyManager.Model.UserAccount", "Owner")
                        .WithMany("Keys")
                        .HasForeignKey("UAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BolomorzKeyManager.Model.Password", b =>
                {
                    b.HasOne("BolomorzKeyManager.Model.UserAccount", "Owner")
                        .WithMany("Passwords")
                        .HasForeignKey("UAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BolomorzKeyManager.Model.UserAccount", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Passwords");
                });
#pragma warning restore 612, 618
        }
    }
}
